[tool.poetry]
name = "slimplectic-jax"
version = "0.1.0"
description = ""
authors = ["Joshua Coles <josh@coles.to>"]
readme = "README.md"
packages = [{include = "slimplectic_jax"}]

[tool.poetry.dependencies]
python = "^3.9"
jax-metal = "^0.0.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

